# Generated by Django 3.2.7 on 2021-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='career',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
